openapi: 3.0.0
info:
  title: FixMate API
  version: 1.0.0
  description: API documentation for FixMate Local Services Finder
servers:
  - url: http://localhost:5000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    BookingStatus:
      type: string
      enum: [pending, accepted, rejected, in-progress, completed]

security:
  - bearerAuth: []

paths:
  /api/auth/register:
    post:
      summary: Register user or service provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone:
                  type: string
                role:
                  type: string
                  enum: [user, service-provider]
      responses:
        '201':
          description: Successfully registered

  /api/auth/login:
    post:
      summary: Login user or provider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Login successful

  /api/users/profile:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile details

  /api/providers/nearby:
    get:
      summary: Get nearby providers
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
        - name: lng
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: List of nearby providers

  /api/providers/{id}:
    get:
      summary: Get provider details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Provider profile

  /api/bookings:
    post:
      summary: Book a provider
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: providerId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                time:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Booking created

  /api/bookings/my:
    get:
      summary: Get user's bookings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user bookings

  /api/bookings/provider:
    get:
      summary: Get provider's bookings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of provider bookings

  /api/bookings/{bookingId}/status:
    put:
      summary: Update booking status
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/BookingStatus'
      responses:
        '200':
          description: Status updated

  /api/bookings/{bookingId}/contact:
    get:
      summary: Get provider contact if allowed
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: bookingId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact details

  /api/reviews:
    post:
      summary: Submit a review
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                providerId:
                  type: string
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        '201':
          description: Review submitted

  /api/reviews/{providerId}:
    get:
      summary: Get reviews for provider
      parameters:
        - in: path
          name: providerId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Review list with average

  /api/dashboard/user:
    get:
      summary: Get user dashboard data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard data

  /api/dashboard/provider:
    get:
      summary: Get provider dashboard data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard data

  /api/notifications:
    get:
      summary: Get current user's notifications
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of notifications

  /api/notifications/{notificationId}/read:
    put:
      summary: Mark a notification as read
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: notificationId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification marked as read
